spring.application.name=senseisystem

spring.datasource.url=jdbc:postgresql://localhost:5432/academia
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enebled=true
spring.flyway.locations=classpath:db/migration